apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ubuntu
  namespace: default
spec:
  selector:
    matchLabels:
      run: my-ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        run: my-ubuntu
    spec:
      containers:
        - name: my-nginx
          image: ubuntu:22.04
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: token
          command:
            - /bin/bash
            - -c
            - sleep 36000

